### ISSUE TITLE
Add constructor to MaxWidthCellManager

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#106]

**Comment by cwkang1998** [comment]
Can I try this out?

**Comment by leolara** [comment]
Yes @cwkang1998

**Comment by cwkang1998** [comment]
Hey @leolara I think its already implemented as seen https://github.com/privacy-scaling-explorations/chiquito/blob/main/src/plonkish/compiler/cell_manager.rs#L239.

**Comment by leolara** [comment]
@cwkang1998 you are right 🤣 do you want to do this one https://github.com/privacy-scaling-explorations/chiquito/issues/109 or any other that interest you?

**Comment by cwkang1998** [comment]
@leolara I would like give #109 a try! Can you assign me?

**Comment by leolara** [comment]
@cwkang1998 please post a comment in that issue, the system does not let me to assign it until you comment there :-)
