### ISSUE TITLE
CompilerConfigBuilder

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#109]
Create a builder patter struct that allows to give some options and will create a compiler config for us. It uses a fluid interface, each method returns a `&mut` of `self`.

The interface is this:

`config_builder().max_width(10).build()` will return a config with MaxWidthCellManager{max_height, same_height: true}, SimpleStepSelectorBuilder

`config_builder().max_height(1).build()` will return a config with MaxWidthCellManager, SimpleStepSelectorBuilder

Things that have no Cell Manager should throw a panic.

Like:

`config_builder().max_width(10).max_height(2).build()`

**Comment by cwkang1998** [comment]
Would like to give this a try!

**Comment by leolara** [comment]
Use Option to keep the options in a struct, then put an algorithm in build() based on those values.

**Comment by 000wan** [comment]
Hi @cwkang1998 :)
I want to gently ask how the task is going on, since I'm interested in this.
If possible, I'd like to work on this issue; and if not it's totally fine, I'll find another one to work on.

**Comment by leolara** [comment]
@cwkang1998 are you working on this?

**Comment by cwkang1998** [comment]
Yup I am working on this, sorry for the delay, will get the PR up soon

**Comment by cwkang1998** [comment]
Sorry for taking a long time, first revision at #138.
