### ISSUE TITLE
Enable automatic generation of `instance` for Plaf backend

### ISSUE THREAD

**Issue by qwang98** [privacy-scaling-explorations/chiquito#129]
Halo2 mockprover::run requires an instance parameter, which Rust Chiquito automatically generates under the `instance` function in halo2.rs:
```
 pub fn instance(&self) -> Vec<Vec<F>> {
        if !self.compiled.circuit.exposed.is_empty() {
            if let Some(witness) = &self.witness {
                return vec![self.compiled.instance(witness)];
            }
        }
        Vec::new()
    }
```

which calls:
```
fn instance(&self, witness: &Assignments<F>) -> Vec<F> {
        let mut instance_values = Vec::new();
        for (column, rotation) in &self.circuit.exposed {
            let values = witness
                .get(column)
                .unwrap_or_else(|| panic!("exposed column not found: {}", column.annotation));

            if let Some(value) = values.get(*rotation as usize) {
                instance_values.push(*value);
            } else {
                panic!(
                    "assignment index out of bounds for column: {}",
                    column.annotation
                );
            }
        }
        instance_values
    }
```

An example of using the public `instance()` function in fibonacci.rs (or really just any example file that exposes public signal):
```
let prover = MockProver::<Fr>::run(7, &circuit, circuit.instance()).unwrap();
```

We want to enable the same for the Plaf backend. The final result should enable us to call `instance()` no plaf circuits as well:
```
let prover_plaf = MockProver::<Fr>::run(8, &plaf_circuit, plaf_circuit.instance()).unwrap();
```

Note that in Chiquito, the instance values are collected from the `Assignment` object indexed by the `instance` column.

More details to be filled for Plaf.

As a background, Plaf is a good visualization tool that checks whether polynomial constraints are identical among different Halo2 constructions (say between Chiquito and Halo2). It also has pretty print methods for witness and fixed assignments, that are good for debugging in general.

**Comment by leolara** [comment]
Done in plaf
