### ISSUE TITLE
Add chiquito to PSE website 

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#137]
https://github.com/privacy-scaling-explorations/website-v2/tree/main/data/projects

**Comment by Utilitycoder** [comment]
Please assign this to me.

**Comment by leolara** [comment]
@Utilitycoder done

**Comment by Utilitycoder** [comment]
@leolara, How best would you fill these fields:

``` tags: {
    keywords: ["Reputation", "Identity"],
    themes: ["build"],
    types: ["Infrastructure/protocol"],
    builtWith: ["ethereum attestation service", "halo2", "ethers.rs"],

**Comment by leolara** [comment]
Check others, and propose what would be the fields in your opinion for chiquito, then we discuss.

**Comment by Utilitycoder** [comment]
Alright. Look at this draft: https://github.com/Utilitycoder/website-v2/blob/chiquito/data/projects/chiquito.ts

**Comment by leolara** [comment]
Created PR: https://github.com/privacy-scaling-explorations/website-v2/pull/170
