### ISSUE TITLE
prelude mode for quick start experience (suggested by CC)

### ISSUE THREAD

**Issue by qwang98** [privacy-scaling-explorations/chiquito#14]
In the future PR, we can define a "prelude" module for a quick start experience.
Instead of importing all the required modules, users can get started with just one line, use chiquito::prelude::*;.

See this plotters example.
https://docs.rs/plotters/latest/plotters/prelude/struct.EmptyElement.html#example

**Comment by leolara** [comment]
I think the user all that needs now is chiquito::dsl::* and chiquito::dsl::cb::* inside the lambda that defines the main circuit. If not we should try to achieve this.

**Comment by leolara** [comment]
This is done
