### ISSUE TITLE
Degree 2 reduction for Chiquito circuit

### ISSUE THREAD

**Issue by qwang98** [privacy-scaling-explorations/chiquito#169]
Reduce Chiquito Expr to degree 2 or less polynomials, so that we can plug in R1CS based backend + folding in the future.

eSTARK uses arbitrary degree 2 polynomials, so things like a * b + c * d will work.

R1CS uses degree 2 polynomials with 1 multiplication only (before expansion) but unlimited addition, so things like (a + c) * (b + d) will work but a * b + c * d won't.

**Comment by leolara** [comment]
We have done de reducing to arbitrary degree, but not the R1CS specific reduction

**Comment by leolara** [comment]
I close it and I create one specific for R1CS
