### ISSUE TITLE
apidocs.pecadorplonkish.xyz is not safe

### ISSUE THREAD

**Issue by 0xbok** [privacy-scaling-explorations/chiquito#196]
The link to docs in "About" section https://apidocs.pecadorplonkish.xyz/ says "Your connection is not private". Perhaps the certificate has expired?

**Comment by leolara** [comment]
Hello, the actual link should be https://docs.pecadorplonkish.xyz . Would you like to create a PR to dix it?

**Comment by 0xbok** [comment]
This is in the repo’s About section. I don’t think it can be changed with code, only from the github UI by an admin.

**Comment by leolara** [comment]
Thanks I fixed it there!! It is still in the README, but I will fix it next week.

**Comment by 0xbok** [comment]
@leolara, made a pr ^
