### ISSUE TITLE
Add missing arithmetic operators to parser

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#216]
We should have all that are in section "Arithmetic operators" and "Bitwise operators" here https://docs.circom.io/circom-language/basic-operators/#arithmetic-operators

The operator priority should be like in circom that is the same as in rust.

**Comment by rutefig** [comment]
In this branch: https://github.com/privacy-scaling-explorations/chiquito/tree/rutefig/205-add-missing-binary-operators-to-lalrpop-and-ast
It is linked to the issue #205

**Comment by leolara** [comment]
@rutefig why do you link to a branch instead of sending a PR?

**Comment by rutefig** [comment]
> @rutefig why do you link to a branch instead of sending a PR?

It was just to keep track that this issue is being done on the same branch as the issue #205 because it is related, when the PR is ready I will link it here too
