### ISSUE TITLE
Semantic analyser: state variables can only be declared in the top level block

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#223]
They cannot be declared for example inside an if block.

**Comment by leolara** [comment]
@rutefig I passed this one to @gmridul

**Comment by rutefig** [comment]
This is already done here: https://github.com/privacy-scaling-explorations/chiquito/blob/2d6236f73b5228c84365a76cf8364bed49f0ac5f/src/compiler/semantic/rules.rs#L84
