### ISSUE TITLE
Fibo example with MaxWidthCellManager

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#24]
There is a new cell manager, that allows in theory to compile the fibo example to one column, so a step takes 3 rows.

In the same file the fibo example should be compiled and run the mockProver with both, the SingleRowCellManager and with MaxWidthCellManager { max_width: 1, same_height: true }.

**Comment by qwang98** [comment]
See pr#25 for a question. Thanks.

**Comment by saeyoon17** [comment]
Hi, I am participating in PSE's Summer Contribution Camp. Is the issue still valid? If it is, can I work on it?
