### ISSUE TITLE
Running keccak example shouldn't generate files (or it can be an option)

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#258]

**Comment by alxkzmn** [comment]
I'm now refactoring the examples in relation to #255 and I'll remove the file generation because it was only used for plaf.

**Comment by alxkzmn** [comment]
This was effectively resolved by https://github.com/privacy-scaling-explorations/chiquito/pull/263 (file generation code was removed together with plaf).
