### ISSUE TITLE
Investigate why the github pages URL is reset

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#28]
We have the domain apidocs.pecadorplonkish.xyz set up for chiquito docs, and it works, after you set it up in Settings. However, it seems that after a push, the domain is reset to the PSE gihub pages one.

Find out why is this happening and correct it.

**Comment by leolara** [comment]
perhaps @ChihChengLiang knows about this stuff?

**Comment by ChihChengLiang** [comment]
I see docs correctly rendered on https://apidocs.pecadorplonkish.xyz

**Comment by leolara** [comment]
Yes but when there is a new commit it stops working and the domain reverts to PSE's

**Comment by ChihChengLiang** [comment]
I hear you. I haven't seen this Github page behavior before, so that it might need some investigation from @qwang98.

**Comment by qwang98** [comment]
Should be resolved by pr#30. @leolara after you approve, I can merge and see if the custom domain is automatically setup in CNAME.
