### ISSUE TITLE
Implement lexer/parser for hyper transition

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#290]
Having this syntax:

```
fc', fd' <== mB(fa, fb) --> other;
```

In the AST, this is represented with a new Enum variant at the same level of transition. This is: `Statement::HyperTransition`. Probably in the AST we will need a Expression::Call

**Comment by alxkzmn** [comment]
@leolara should we also implement this variant right away?
```
    -> other {
           fc', fd' <== mB(fa, fb);
    }
```
