### ISSUE TITLE
Plaf backend

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#33]
Implement backend that takes our IR and convert it to Plaf format.

We could be tempted to compile our circuit to halo2 and then import that into plaf. But that would create other problems down the line. Plaf should be supported natively as a backend.

Plaf will not support Halo2 imported columns and expressions, hence if in the process of compiling to Plaf any of these are found we should terminate with an error.

In the end we should have a module backend/plaf.rs with a function like [chiquito2Halo2](https://github.com/privacy-scaling-explorations/chiquito/blob/main/src/backend/halo2.rs#L28) named chiquito2plaf that will return a plaf struct from a (ir::Circuit)[https://github.com/privacy-scaling-explorations/chiquito/blob/main/src/ir.rs#L12] .

**Comment by qwang98** [comment]
First pass ready for review @leolara
