### ISSUE TITLE
Compatibility problem among variable height cell manager, padding, and q_last

### ISSUE THREAD

**Issue by qwang98** [privacy-scaling-explorations/chiquito#37]
See closed pr#25. End goal is to make the Fibonacci example using variable height cell manager run without error.

**Comment by qwang98** [comment]
Related to the following TODOs from @leolara's roadmap: https://hackmd.io/@leolara/H1aisIi43

[TODO] Managed padding
Padding that is more automatic to circuits. This is connected to the fixed height of circuits.

[TODO] Other Fixed height cell managers
Fixed height cell manager are simpler in terms of calculating their fixed height and hence padding and q_last.

**Comment by qwang98** [comment]
# Notes from Leo

## Solution #1
padding added to trace function
adding a step to the end (ctx.padding, add one step)
- trace function but only add one step
can let user define their own padding
q_last is for the last row in the PLONKish table
q_first is the row after q_last and that can create security issues so we need q_last and q_first

## Solution #2
- enforce the last row before any padding is of a certain step type
- constrain the next row to be padding and its next one to be padding as well

## Miscellaneous
why is padding needed?
- halo2 will auto generate 0 witness value if you don’t assign and that can break the circuit

**Comment by leolara** [comment]
This is solved for circuits with all the steps with the same height
