### ISSUE TITLE
Lookup abstraction

### ISSUE THREAD

**Issue by qwang98** [privacy-scaling-explorations/chiquito#44]
Abstract a lookup table data type so that a Chiquito circuit can import and export it. Allows for circuit inter-operability.

**Comment by qwang98** [comment]
# WIP NOT READY FOR REVIEW
# Background
`ir:Circuit` has a `lookups` field that contains all lookups, which are collected from a loop over all step types. Note that in the dsl and ast, lookups are defined on the step type level.
- ir with all lookups:
```
pub struct Circuit<F, TraceArgs, StepArgs> {
    ...
    pub step_types: HashMap<u32, Rc<StepType<F, StepArgs>>>,
    ...
    pub lookups: Vec<PolyLookup<F>>,
    ...
}

pub struct PolyLookup<F> {
    pub annotation: String,
    pub exprs: Vec<(PolyExpr<F>, PolyExpr<F>)>,
}
```
- ast lookups defined on the step type level:
```
pub struct StepType<F, Args> {
   ...
    pub lookups: Vec<Lookup<F>>,
   ... 
}

pub struct Lookup<F> {
    pub annotation: String,
    pub exprs: Vec<(Constraint<F>, Expr<F>)>,
    pub enable: Option<Constraint<F>>,
}
```

# Proposal
In dsl, on the CircuitContext level:
- `export_lookup(&self, step_type: &StepTypeHandler, lookup_index: usize) -> Vec<Expr<F>>`, where Expr<F> are destination columns to export.
- `export_lookup_all(&self) -> Vec<Expr<F>>`, which exports all destination columns of all step types of a circuit.
- `import_lookup`

**Comment by qwang98** [comment]
@leolara

My first pass of the design. Let me know if you have any comments.

**Comment by qwang98** [comment]
let thetable = ctx.new_lookup(DA, DB, DC)

ctx.add_lookup(thetable.match(SA, SB, SC))

ctx.add_lookup(thetable.match(SA, SB, SC).enable(E))

**Comment by leolara** [comment]
This is onde
