### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/chiquito#5]
A Readme file can help contributors to get up to speed with the project. 

The content should contain

1. Project descriptions
2. Getting started and a pointer to examples
3. testing and lints
4. licenses

References: https://github.com/leolara/chiquito-presentation

**Comment by qwang98** [comment]
First draft done at pull request #8: https://github.com/privacy-scaling-explorations/chiquito/pull/8
