### ISSUE TITLE
Add unit tests to DSL

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#75]
To the structs in this file: https://github.com/privacy-scaling-explorations/chiquito/blob/main/src/frontend/dsl/mod.rs

Add unit tests.

**Comment by nullbitx8** [comment]
Hi I'd like to pick this up! 
Starting on my fork/branch https://github.com/nullbitx8/chiquito/tree/issue-75-add-unit-tests-to-dsl

**Comment by leolara** [comment]
I think @rutefig you are working on this too?
