### ISSUE TITLE
An error occurs when replacing SingleRowCellManager with MaxWidthCellManager.

### ISSUE THREAD

**Issue by 10to4** [privacy-scaling-explorations/chiquito#78]
When replacing SingleRowCellManager with MaxWidthCellManager in the Poseidon example, the code executes the compile_phase1 function, which calls the place_fixed_assignments function, leading to an error. 
It appears that the error stems from the fixed signal not being processed in the MaxWidthCellManager's place function, resulting in that fixed is an empty field in the Placement structure. So when it calls the get_fixed_placement function, it get an error message 'fixed placement not found'.

        let config = config(
            MaxWidthCellManager::new(2, true),
            SimpleStepSelectorBuilder {},
        );
        let (_, constants_table) =
            ctx.sub_circuit(config.clone(), poseidon_constants_table, lens.n_inputs + 1);
        let (_, matrix_table) =
            ctx.sub_circuit(config.clone(), poseidon_matrix_table, lens.n_inputs + 1);
        let params = CircuitParams {
            lens,
            constants_table,
            matrix_table,
        };
        let (poseidon, _) = ctx.sub_circuit(config, poseidon_circuit, params);

The error message:
thread 'main' panicked at 'fixed placement not found', ./chiquito/src/compiler.rs:702:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/option.rs:1874:5
   5: core::option::Option<T>::expect
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/option.rs:738:21
   6: chiquito::compiler::Compiler<CM,SSB>::place_fixed_assignments
             at ./src/compiler.rs:700:21
   7: chiquito::compiler::Compiler<CM,SSB>::compile_fixed
             at ./src/compiler.rs:521:38
   8: chiquito::compiler::Compiler<CM,SSB>::compile_phase1
             at ./src/compiler.rs:357:9
   9: chiquito::dsl::sc::SuperCircuitContext<F,MappingArgs>::sub_circuit
             at ./src/dsl/sc.rs:58:34
  10: poseidon::poseidon_super_circuit::{{closure}}
             at ./examples/poseidon.rs:13435:13
  11: chiquito::dsl::sc::super_circuit
             at ./src/dsl/sc.rs:106:5
  12: poseidon::poseidon_super_circuit
             at ./examples/poseidon.rs:13428:5
  13: poseidon::main
             at ./examples/poseidon.rs:13468:25
  14: core::ops::function::FnOnce::call_once
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by 10to4** [comment]
Thanks for @leolara. I have successfully resolved the problem. It turns out that the fixed circuit should not utilize the MaxWidthCellManager; rather, it should use the SingleRowCellManager. By segregating the managers for different subcircuits. Sub circuits with the "fixed" signal are now handled using the SingleRowCellManager, while the main circuit utilizes the MaxWidthCellManager, the error is resolved.

        let single_config = config(SingleRowCellManager {}, SimpleStepSelectorBuilder {});
        let (_, constants_table) = ctx.sub_circuit(
            single_config.clone(),
            poseidon_constants_table,
            lens.n_inputs + 1,
        );
        let (_, matrix_table) =
            ctx.sub_circuit(single_config, poseidon_matrix_table, lens.n_inputs + 1);
        let params = CircuitParams {
            lens,
            constants_table,
            matrix_table,
        };
        let maxwidth_config = config(
            MaxWidthCellManager::new(2, true),
            SimpleStepSelectorBuilder {},
        );
        let (poseidon, _) = ctx.sub_circuit(maxwidth_config, poseidon_circuit, params);

**Comment by leolara** [comment]
This will be solved here: https://github.com/privacy-scaling-explorations/chiquito/issues/97
