### ISSUE TITLE
Add unit tests to LookupBuilder

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#93]
To structs in this file: https://github.com/privacy-scaling-explorations/chiquito/blob/main/src/frontend/dsl/lb.rs

**Comment by motemotech** [comment]
Hi, can I work on this issue?

**Comment by qwang98** [comment]
@trangnv Still on this?

**Comment by trangnv** [comment]
@motemotech Yes you can work on this!

**Comment by motemotech** [comment]
Hi, do you have any naming rules for branchs in this prj?

**Comment by leolara** [comment]
@motemotech not really rules but we usually do githandle/something-meaningfull

**Comment by motemotech** [comment]
ok, gotcha.

**Comment by motemotech** [comment]
@leolara 
Hi, I finally finished adding test, but seems I do not have permission to push my branch.
Could you add me as a member of this repository?

**Comment by leolara** [comment]
You have to create a branch in your fork, and then submit a PR @motemotech

**Comment by motemotech** [comment]
@leolara 
Hi! Sorry for being late.
Is this good?
https://github.com/privacy-scaling-explorations/chiquito/pull/148

**Comment by leolara** [comment]
@motemotech the PR has unsolved problems
