### ISSUE TITLE
Add unit tests for Python

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#94]
Add necessary infrastructure for unit test in Python and write at least one unit test to show it works.

Add to github actions to avoid merging if the python tests do not pass.

**Comment by indextree** [comment]
Can I pick up this issue? If there are some supplementary materials for this issue, I'd like to take for them :)

**Comment by leolara** [comment]
@trangnv are you working on this or I give it to @indextree ?

**Comment by trangnv** [comment]
Please go ahead and work on it @indextree 
Thanks

**Comment by leolara** [comment]
@indextree so perhaps you can do this in several PRs, like chose a component and send a PR with unit tests for that one.

**Comment by indextree** [comment]
@leolara Thanks. For which python code should I write unit test? Sorry for the late reply, because I thought I should write all unit test code for python frontend source. Can I write unit test code simply from fibonacci example?

**Comment by qwang98** [comment]
I think it's basically for all the Python frontend source and that's why it can be in several PRs.

What do you mean "write from fibonacci example"?

**Comment by indextree** [comment]
@qwang98 Oh I misunderstood. Thanks for the reply. Please just ignore that.
