### ISSUE TITLE
SimpleStepSelectorBuilder case when there is only one step

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#95]
The SimpleStepSelectorBuilder creates a column for each step type, that gets to be 1 in the row where a step instance of that type starts.

When there is only one step type we don't need any column, because all steps are of this step type.

Make SimpleStepSelectorBuilder to don't add any columns where there is a column, and create a StepSelector that works without any column.

**Comment by 000wan** [comment]
Hi, may I work on this issue?

**Comment by leolara** [comment]
assigned @000wan
