### ISSUE TITLE
Make MaxWidthCellManager work with shared signals

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#96]
Currently MaxWidthCellManager does not work with shared signals (SingleRowCellManager does).

Make them work.

What is a shared signal?

A shared signal is a signal that is shared by all the steps, and you can do rotation arbitrarily between all the steps, but they only work when the circuit has all the steps with the same height. Forward signals are also shared between steps, but you can only do a rotation to the next step, however they work on circuits with steps of different height.

**Comment by e3243eric** [comment]
I would like to take this on. I've looked into SingleRowCellManager and MaxWidthCellManager. Is there a difference between them, where SingleRowCellManager only has one fixed height, while MaxWidthCellManager allows for multiple heights with a maximum size?

**Comment by leolara** [comment]
Yes, that is the difference

**Comment by leolara** [comment]
@e3243eric assigned

**Comment by rutefig** [comment]
@e3243eric are you working on this? Otherwise can I take it?
