### ISSUE TITLE
Make MaxWidthCellManager work with fixed signals

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#97]
Currently only SingleRowCellManager can handle fixed signals. Make it work on MaxWidthCellManager.

Because the fixed signals use different columns than the other signals, we need a new parameter called `max_width_fixed`.

**Comment by atsupontio** [comment]
I would like to try working on this issue!

**Comment by leolara** [comment]
@atsupontio assigned

**Comment by atsupontio** [comment]
I dont know where a new parameter `max_width_fixed` should be added, should it be added to the `MaxWidthCellManager` structure and used separately from max_width?

Also, I have an implementation in [my branch](https://github.com/atsupontio/chiquito/blob/add_fixed_signals_%2397/src/plonkish/compiler/cell_manager.rs) without `max_width_fixed` added.
I ran poseidon.rs with this implementation as` let single_config = config(MaxWidthCellManager::new(2, true), SimpleStepSelectorBuilder {});` #78 and it worked fine.

Is there anything I should fix?

**Comment by leolara** [comment]
MaxWidthCellManager should have a new field called max_width_fixed, also rename max_width to max_width_advice.

https://github.com/privacy-scaling-explorations/chiquito/blob/main/src/plonkish/compiler/cell_manager.rs#L233

**Comment by atsupontio** [comment]
I added` max_width_fixed` and renamed `max_width` to `max_width_advice`.
There is implementation in [my branch](https://github.com/atsupontio/chiquito/tree/add_fixed_signals_%2397), so please take a look!
And, please let me know if anything else is required.

**Comment by leolara** [comment]
@atsupontio for us to review code has to be sent on a PR, it can be draft mode if you are unsure.
