### ISSUE TITLE
Example: Merkle inclusion Proof

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#98]
Inspired by this circom code: https://github.com/semaphore-protocol/semaphore/blob/main/packages/circuits/tree.circom

Create a similar proof using the rust front-end, you can use mimc7 or poseidon for the example folder

**Comment by cotoneum** [comment]
I would like to try working on this issue!

**Comment by leolara** [comment]
@cotoneum assigned

**Comment by sraver** [comment]
@leolara I actually have added this circuit in the semaphore-chiquito repository. Do you think we should move it also into here?

**Comment by leolara** [comment]
Closed because @sraver did it, could we put a link to that here?
